import board

CFG_DEBUG: bool = True

CFG_NEOPIXEL_PIN: int = board.GP28
CFG_NEOPIXEL_LED_COUNT: int = 12
CFG_NEOPIXEL_MAX_BRIGHTNESS: float = 1.0

CFG_ENCODER_INVERT: bool = False
CFG_ENCODER_CLK_PIN = board.GP20
CFG_ENCODER_DT_PIN = board.GP19